### ISSUE TITLE
missing hover animations in bookmark items under folders in bookmark bar

### ISSUE THREAD

**Issue by livingator** [1280px/rainfox#4]
same as subject, hopefully it'd be fixed

**Comment by livingator** [comment]
just found out it also happens to drop down menu items

**Comment by jnviita** [comment]
Same issue here - hover highlight missing from menu bar, context and bookmarks menus. Strangely they do work in the hamburger menu. Firefox 96.0, Linux, Xcfe.

**Comment by 1280px** [comment]
Yes, classic context menus in Linux are currently broken. 
Panels (why not use just one type of menus for everything? that's a good question) work fine though, that's why some menus work fine

Thankfully it seems to be independent of DE so guess it won't be too hard to fix

**Comment by livingator** [comment]
> Yes, classic context menus in Linux are currently broken.
> 

forgot to say but i'm on windows 10 firefox 96.0.1 here (so i guess it's not just linux)

**Comment by 1280px** [comment]
> i'm on windows 10 firefox 96.0.1

That's weird, on Win10 x86 WM cmenu items are animated as intended:
![VirtualBoxVM_meh2PkjgHh](https://user-images.githubusercontent.com/71165491/150382197-8508c37f-b80a-4786-b417-559a040183b6.gif)


Are you sure `layout.css.color-mix.enabled` key is set to **`true`**?

**Comment by livingator** [comment]
> 
> Are you sure `layout.css.color-mix.enabled` key is set to **`true`**?

i thought i had it on true before the recent rainfox update, guess it's just my fault for not checking whether it's on or not 1st. it's all good now sorry

**Comment by 1280px** [comment]
Okay, glad to hear it's working now :)
I thinj this issue is resolved, so I'll open another one specifically for cmenu animations in Linux
