### ISSUE TITLE
How to turn off features?

### ISSUE THREAD

**Issue by fernandossmm** [1280px/rainfox#8]
In the README it says features can be turned off modularly, but it doesn't say how. Deleting files maybe? Should probably be explained.

**Comment by 1280px** [comment]
No, much easier. Open `userChrome.css` and you'll see a bunch of `@import` command with short description:
```
•••

To disable/enable some part of the style, add/remove "/* " before its @import. Example:
@import "userChromeReplaceEverythingWithPizza.css"                [ ENABLED ]
/* @import "userChromeReplaceEverythingWithPizza.css"             [ DISABLED ]

•••

/* ### ###  Elem Animations & Rounding  ### ### */
@import "userChromeAnimations.css";

/* ### ###    PhotonUI icons (.icon)    ### ### */
@import "userChromeIcons.css";

/* ### ###   Hide Bloaty/Useless Opts   ### ### */
@import "userChromeOptHider.css";

•••
```
Let's say you want to disable Photon icons. To do this, add `/*` before `@import "userChromeIcons.css"`, like this:
```
•••

/* ### ###    PhotonUI icons (.icon)    ### ### */
/* @import "userChromeIcons.css";

•••
```
Do the opposite to (re-)enable a disabled feature. Hope this helps

**Comment by 1280px** [comment]
I guess the issue is now resolved, also added the link to it in README for clarity
